### ISSUE TITLE
Doesn't this bypass the react-fiber ?

### ISSUE THREAD

**Issue by dtuyenle** [esxjs/esx#9]
Seems like this not using virtual dom ?

**Comment by davidmarkclements** [comment]
yes that's correct

**Comment by davidmarkclements** [comment]
this is a backend optimisation - the idea is you use template strings with this optimization for backend and react.createElement on the frontend (use transpiling from JSX or if you prefer native language features, ESX, to fulfil this).

**Comment by dtuyenle** [comment]
Thanks for your quick response. Here is another question. If the whole htnl already cached then doesnt it mean this is kinda irrelevant ?

**Comment by dtuyenle** [comment]
Yea I agree it has its own use case. Please close this issue. Thanks
